-- Winbar component using lsp
return {
    {
        "Bekaboo/dropbar.nvim",
        dependencies = {
            "nvim-telescope/telescope-fzf-native.nvim",
            build = "make"
        },
        event = "VeryLazy",
        keys = {
            { "<Leader>;", function() require("dropbar.api").pick() end,                desc = "Dropbar: Pick symbols in winbar" },
            { "[;",        function() require("dropbar.api").goto_context_start() end,  desc = "Dropbar: Go to start of current context" },
            { "];",        function() require("dropbar.api").select_next_context() end, desc = "Dropbar: Select next context" },
        },
        config = function()
            require("dropbar").setup({
                menu = {
                    win_configs = {
                        border = "rounded",
                    },
                },
                sources = {
                    treesitter = {
                        valid_types = {
                            "array",
                            "boolean",
                            "break_statement",
                            "call",
                            "case_statement",
                            "class",
                            "constant",
                            "constructor",
                            "continue_statement",
                            "delete",
                            "do_statement",
                            "element",
                            "enum",
                            "enum_member",
                            "event",
                            "for_statement",
                            "function",
                            "h1_marker",
                            "h2_marker",
                            "h3_marker",
                            "h4_marker",
                            "h5_marker",
                            "h6_marker",
                            "if_statement",
                            "interface",
                            "keyword",
                            "macro",
                            "method",
                            -- "module",
                            "namespace",
                            "null",
                            "number",
                            "operator",
                            "package",
                            "pair",
                            "property",
                            "reference",
                            "repeat",
                            "rule_set",
                            "scope",
                            "specifier",
                            "struct",
                            "switch_statement",
                            "type",
                            "type_parameter",
                            "unit",
                            "value",
                            "variable",
                            "while_statement",
                            "declaration",
                            "field",
                            "identifier",
                            "object",
                            "statement",
                        },
                    },
                },
            })
        end,
    },
}
